### ISSUE TITLE
chyba v configu po instalaci composerem

### ISSUE THREAD

**Issue by iiic** [minetro/micro-website-sandbox#1]
Po instalaci composerem (a vytvoření cache adresářů) to píše

Service 'routing.router': Service of type Nette\Application\Routers\RouteList needed by Minetro\Micro\Routing\RouterManager::create() not found. Did you register it in configuration file?

předchozí verze hned fungovala :(

**Comment by f3l1x** [comment]
Diky za report. Mrknu na to.

Jenom dotaz, registroval jsi v configu router?

**Comment by f3l1x** [comment]
Tak uz jsem to opravil.

https://github.com/minetro/micro-website-module/commit/55b677d702cd1c5e105f3bc7911e75305e96e3ec

**Comment by iiic** [comment]
jop, funguje, díky :) to byla rychlost
